googleads/publisher-ads-lighthouse-plugin

lighthouse-plugin-ad-speed-insights/yarn.lock
Resolve found security vulnerability found in `just-extend < 4.0.0` by upgrading `sinon` from 5.0.7 to 5.1.1.
=> Resolve found security vulnerability found in `just-extend < 4.0.0`.

lighthouse-plugin-ad-speed-insights/audits/async-ad-tags.js, lighthouse-plugin-ad-speed-insights/audits/static-ad-tags.js, lighthouse-plugin-ad-speed-insights/test/audits/async-ad-tags_test.js, lighthouse-plugin-ad-speed-insights/utils/resource-classification.js
Resolve https://github.com/googleads/ad-speed-insights/issues/4
This is a temporary fix, this assumes that preloaded tags are loaded using `async` tag. Will explicitly check in future.
=> Fix async audit for cases where tag is preloaded.

lighthouse-plugin-ad-speed-insights/package.json, lighthouse-plugin-ad-speed-insights/yarn.lock
Move Lighthouse from devDependencies to peerDependencies for proper plugin usage.
This resolves https://github.com/googleads/ad-speed-insights/issues/8
=> Move Lighthouse from devDependencies to peerDependencies for proper

lighthouse-plugin-ad-speed-insights/audits/ad-blocking-tasks.js, lighthouse-plugin-ad-speed-insights/test/audits/ad-blocking-tasks_test.js
Change log:
- Include all long tasks before ad responses, not ones that directly block the ad response.
- Use `duration` rather than `selfTime` to find long tasks. Previously the audit was skipping tasks that were composed of many small functions. Note that child and parent long tasks may both be included, but only if the child has a distinct URL from its parent.
- Show at most 10 long task
We should to consider tuning the failing conditions for this audit (e.g. a single 51 ms task seems relatively minor and should not be failing)
=> Expand the scope of the long tasks audit

lighthouse-plugin-ad-speed-insights/audits/ad-render-blocking-resources.js, lighthouse-plugin-ad-speed-insights/plugin.js
This PR adds the render-blocking resource audit result under ad performance since it can play an important role in ad loading. I create a "fork" of the core lighthouse audit so that its table looks similar to other tables in ads audits.
=> Copy the "render blocking resources" audit under ads-performance

lighthouse-plugin-ad-speed-insights/audits/ad-blocking-tasks.js
LH requires URLs to include the protocol to be rendered properly, so I update the results table for the long tasks audit to include the protocols.
=> Include full URLs in long tasks audit so they're rendered correctly

lighthouse-plugin-ad-speed-insights/audits/ad-request-critical-path.js, lighthouse-plugin-ad-speed-insights/utils/bidder-patterns.js, lighthouse-plugin-ad-speed-insights/utils/graph.js
This PR does a few things:
1. Remove false positive script outputs. The previous JSONP heuristic was too broad. I remove this heuristic until we have a better one in place. I don't expect this to matter too much since jsonp is relatively rare today.
2. Abbreviate URLs of overlapping requests with the same path to improve report brevity.
3. Filter out the document and any short (<30ms) requests from output table.
=> Critical path: remove false positives and abbreviate overlapping requests in output

lighthouse-plugin-ad-speed-insights/package.json, package.json
There is no CONTRIBUTING.md in the main directory, causing the link in the README to break. I have corrected this link to go to the Publisher Ads Audits for Lighthouse's contribution guide.
=> Correct contributing link

lighthouse-plugin-ad-speed-insights/utils/graph.js
The audit was taking too long so I optimize the algorithm. Most of the slowness was caused by repeatedly searching `traceEvents`, which is large and searched often for some pubs. I also use a map (keyed by url) instead of an array for searching network records. This doesn't offer a huge speedup since the array is small, but I did it anyway.
=> Optimize critical path audit

lighthouse-plugin-ad-speed-insights/utils/graph.js
1. Fixes an error where an exception will be thrown in computing the critical path of ad loading if the ad tag is not loaded. Now the method returns the empty set rather than throwing.
2. Fixes cases where some false positive requests show up after the main ad request
=> Fix some edge cases in computing critical paths

lighthouse-plugin-ad-speed-insights/audits/ad-request-from-page-start.js, lighthouse-plugin-ad-speed-insights/audits/ad-request-from-tag-load.js, lighthouse-plugin-ad-speed-insights/audits/tag-load-time.js, lighthouse-plugin-ad-speed-insights/messages/en-US.json, lighthouse-plugin-ad-speed-insights/plugin.js, lighthouse-plugin-ad-speed-insights/test/audits/ad-request-from-page-start_test.js, lighthouse-plugin-ad-speed-insights/test/audits/ad-request-from-tag-load_test.js, lighthouse-plugin-ad-speed-insights/test/audits/tag-load-time_test.js
This PR updates top-line metrics to be displayed in seconds for consistency with core lighthouse metrics. Note that detail timestamps (e.g. tables) are still in ms as the relevant time scale is usually O(ms). This is consistent with lighthouse so there are no future plans to update remaining timestamps to seconds.
=> Display metrics in seconds for consistency with Lighthouse core

lighthouse-plugin-ad-speed-insights/audits/static-ad-tags.js, lighthouse-plugin-ad-speed-insights/messages/en-US.json
Estimates the expected uplift (w.r.t. tag load time) of loading gpt statically and displays the result in the audit's failure display title
=> Quantify estimated uplift of static tag loading in audit failure value

lighthouse-plugin-ad-speed-insights/audits/async-ad-tags.js, lighthouse-plugin-ad-speed-insights/test/audits/async-ad-tags_test.js
i.e. ignore sync tags in sub-frames which aren't render blocking of main content. This is intended to fix some false positive failures
=> Only audit for async tag loading in the main frame

lighthouse-plugin-ad-speed-insights/audits/ad-render-blocking-resources.js, lighthouse-plugin-ad-speed-insights/messages/en-US.json
Updates the error message to mention loading the ad tag earlier and display the opportunity for improvement.
=> Update messages for render blocking resources audit

lighthouse-plugin-ad-speed-insights/audits/first-ad-paint.js, lighthouse-plugin-ad-speed-insights/messages/en-US.json
Audit had two issues:
- Missing `traces` in required artifacts
- Did not handle cases where iframes existed but did not have contentful paint. As a follow up we should probably check for contentful paint in any child iframes but the audit now falls back to the first paint
=> Fix errors in first ad paint audit

lighthouse-plugin-ad-speed-insights/audits/first-ad-paint.js, lighthouse-plugin-ad-speed-insights/gatherers/iframe-elements.js, lighthouse-plugin-ad-speed-insights/typings/artifacts.d.ts
Handles cases where (1) an iframe element doesn't have a matching Frame (possibly due to inability to match when there is a DOM ID collision) and (2) when the main document has no child frames
=> Add a few safety checks to the iframe gatherer

lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/first-ad-paint.js, lighthouse-plugin-publisher-ads/audits/tag-load-time.js, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/test/audits/tag-load-time_test.js
Include runtime warnings when:
- No ad is requested
- No ad is rendered
- No GPT tag is loaded
=> Include runtime warnings

lighthouse-plugin-publisher-ads/audits/duplicate-tags.js, lighthouse-plugin-publisher-ads/messages/en-US.json
Include new GPT domain in audit and check by path rather than full URL to account for the same tag being loaded from different hosts.
=> Update duplicate tag audit.

lighthouse-plugin-publisher-ads/audits/script-injected-tags.js, lighthouse-plugin-publisher-ads/utils/graph.js
Regression was introduced in #70 where `NetworkNode` started being used in place of `NetworkRequest` in the `utils/graph.js`.
Follow-up action items are:
- Identify how to prevent this sort of issue in the compiler in general. My understanding is that this slipped through because `any` isn't robustly checked against.
- Develop more robust tests (perhaps via #21)
=> Fix script-injected-tags regression

lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js, lighthouse-plugin-publisher-ads/audits/script-injected-tags.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/utils/network-timing.js
The page time origin would be miscalculated when looking up timings in `getTimingsByRecord` because the array of networks records passed to `getPageRequestTime` was not sorted. (So the wrong time would be returned because it returns the time of the first successful request.) To add to the problem, the array only included "critical requests", which I don't think contains the main document request. (So the wrong time origin would be returned even if the array was sorted.)
I fix the issue by re-computing network records based on `devtoolsLog`. (Note that the computation is cached so there is no serious impact on performance.) As a follow up I would like to refactor code to avoid implicit assumptions.
Tested by running reports. As a follow up lets look at setting up tests based on artifacts.
=> Fix missing resources in the critical path audit

lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js, lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js, lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js, lighthouse-plugin-publisher-ads/audits/idle-network-times.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/messages/en-US.json
Tables that display three columns of numbers are hard to grok so this PR updates tables to show only three columns. For most audits, start time and duration are the most important figures (think long tasks, idle times). However, end time makes more sense than duration for the critical path audit to make initiator comparisons easier. (That is, if a.startTime > b.endTime, then there is a good chance than a depends on b. But it's hard to do the mental math with enough precision of using startTime + duration)
=> Remove endTime column from tables for brevity (from most audits)

lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/test/audits/serial-header-bidding_test.js, lighthouse-plugin-publisher-ads/typings/audits.d.ts, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Fixes a case where some some serial bids would not be caught. Suppose the following three bids:
A: [100, 600]
B: [200, 300]
C: [400, 500]
B and C are mutually serial but the current algorithm would ignore them because they overlap with A. This PR fixes that case
=> Refactor serial bids audit to cover a missing case

index.js
This is a temporary change until simulated results can be verified as accurate.
=> Disable simulated throttling by default.

lighthouse-plugin-publisher-ads/audits/first-ad-paint.js, lighthouse-plugin-publisher-ads/computed/ad-paint-time.js, lighthouse-plugin-publisher-ads/test/utils/resource-classification_test.js, lighthouse-plugin-publisher-ads/utils/network-timing.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Modifies first-ad-paint audit to use impression ping instead of render event, this is to account for complications encountered with OOP IFrames.
Shifts scoring metrics by -300 ms to account for differences in observed metrics.
This is in preparation for https://github.com/GoogleChrome/lighthouse/pull/8979
=> Modifies first-ad-paint audit to use impression ping.

lighthouse-plugin-publisher-ads/audits/first-ad-render.js
=> Enable first ad render audit for AdSense

lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js, lighthouse-plugin-publisher-ads/audits/blocking-load-events.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/render-blocking-tags.js, lighthouse-plugin-publisher-ads/test/smoke/fixtures/no-op-script.js, lighthouse-plugin-publisher-ads/test/smoke/fixtures/no-op-style.css, lighthouse-plugin-publisher-ads/test/smoke/fixtures/render-blocking-tags.html, lighthouse-plugin-publisher-ads/test/smoke/fixtures/script-injected.html, lighthouse-plugin-publisher-ads/test/smoke/smoke-test-dfns.js
The `ad-render-blocking-resources` audit currently only checks for resources blocking first paint but we care about any sync resource that blocks ad loading.
This PR also add support for simulation as part of the refactoring.
=> Update blocking requests audit to check all sync resources

lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
Removed non-ad-related tags, and included additional AdSense tag.
=> Update checked tags in `duplicate-tags` audit.

lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/ad-request-from-tag-load.js, lighthouse-plugin-publisher-ads/audits/bid-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/first-ad-render.js, lighthouse-plugin-publisher-ads/audits/tag-load-time.js
This was implemented to ensure that scores >= .9 did not appear as failing, but this issue has been fixed on the LH side.
=> Remove special-cased score rounding from numeric audits.

lighthouse-plugin-publisher-ads/computed/ad-lantern-metric.js, yarn.lock
This edge is missing whenever gpt.js is prefetched since this introduces two gpt.js requests. As a result, Lighthouse fails to introduce an edge in https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/computed/page-dependency-graph.js#L150
A fix for this particular case in LH seems pretty straightforward but the there are some more general issues with prefetching in the simulation graph. (I'll file issues and/or PRs with some more investigation.) In the meantime, we can fix this on our fairly easily.
=> Enforce gpt->pubads_impl edges in the simulation graph

lighthouse-plugin-publisher-ads/audits/duplicate-tags.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/duplicate-tags.js, lighthouse-plugin-publisher-ads/test/smoke/fixtures/duplicate-tags.html, lighthouse-plugin-publisher-ads/test/smoke/smoke-test-dfns.js
Fixes issue (1) mentioned in #171
=> Only count scripts for duplicate tag loading

lighthouse-plugin-publisher-ads/plugin.js
audit_id | initial_weight | initial_pct | updated_weight | updated_pct | pct_diff
-- | -- | -- | -- | -- | --
tag-load-time | 4 | 11.43% | 4 | 7.02% | -4.41%
bid-request-from-page-start | 4 | 11.43% | 4 | 7.02% | -4.41%
ad-request-from-page-start | 4 | 11.43% | 20 | 35.09% | 23.66%
first-ad-render | 8 | 22.86% | 10 | 17.54% | -5.31%
gpt-bids-parallel | 1 | 2.86% | 1 | 1.75% | -1.10%
serial-header-bidding | 1 | 2.86% | 1 | 1.75% | -1.10%
bottleneck-requests | 1 | 2.86% | 1 | 1.75% | -1.10%
script-injected-tags | 1 | 2.86% | 1 | 1.75% | -1.10%
blocking-load-events | 1 | 2.86% | 1 | 1.75% | -1.10%
ad-render-blocking-resources | 1 | 2.86% | 1 | 1.75% | -1.10%
ad-blocking-tasks | 1 | 2.86% | 1 | 1.75% | -1.10%
ad-request-critical-path | 0 | 0.00% | 0 | 0.00% | 0.00%
ads-in-viewport | 4 | …
=> Reweight audit scoring.

lighthouse-plugin-publisher-ads/audits/duplicate-tags.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
Also update serial header bidding audit to use `MainResource` for detecting the main frame.
=> Only audit for duplicate tag loading in the top frame

lighthouse-plugin-publisher-ads/audits/ads-in-viewport.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Also makes ads in viewport audit ignore AdSense iframes placed out of viewport.
=> Fixes AdSense impl tag regex to handle version number.

lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/first-ad-render.js, lighthouse-plugin-publisher-ads/audits/tag-load-time.js, lighthouse-plugin-publisher-ads/package.json
we had a runWarnings change which also broke you. https://github.com/GoogleChrome/lighthouse/pull/10555
the numericUnit bit was to fix some typechecking. i _think_ it's right but didn't doublecheck.
=> Additional 6.0 fixes

lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js, lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js, lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js, lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/ad-request-from-tag-load.js, lighthouse-plugin-publisher-ads/audits/ad-top-of-viewport.js, lighthouse-plugin-publisher-ads/audits/ads-in-viewport.js, lighthouse-plugin-publisher-ads/audits/async-ad-tags.js, lighthouse-plugin-publisher-ads/audits/bid-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/blocking-load-events.js, lighthouse-plugin-publisher-ads/audits/bottleneck-requests.js, lighthouse-plugin-publisher-ads/audits/duplicate-tags.js, lighthouse-plugin-publisher-ads/audits/first-ad-render.js, lighthouse-plugin-publisher-ads/audits/full-width-slots.js, lighthouse-plugin-publisher-ads/audits/gpt-bids-parallel.js, lighthouse-plugin-publisher-ads/audits/idle-network-times.js, lighthouse-plugin-publisher-ads/audits/loads-gpt-from-sgdn.js, lighthouse-plugin-publisher-ads/audits/script-injected-tags.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/audits/tag-load-time.js, lighthouse-plugin-publisher-ads/audits/viewport-ad-density.js, lighthouse-plugin-publisher-ads/computed/long-tasks.js, lighthouse-plugin-publisher-ads/messages/common-strings.js, lighthouse-plugin-publisher-ads/package.json, lighthouse-plugin-publisher-ads/typings/lighthouse.d.ts, package.json, yarn.lock
- Include 10th percentile scores to support Lighthouse v6.0 `computeLogNormalScore` changes (thanks @brendankenny!).
- Update runWarnings usage (thanks @paulirish!).
- Include numericUnits.
- Other minor fixes.
=> Upgrade to Lighthouse 6.0.0-beta.0

lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js, lighthouse-plugin-publisher-ads/messages/common-strings.js, lighthouse-plugin-publisher-ads/plugin.js, lighthouse-plugin-publisher-ads/test/utils/geometry_test.js, lighthouse-plugin-publisher-ads/utils/geometry.js, lighthouse-plugin-publisher-ads/utils/network-timing.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Measures ad-related layout shift by summing scores across layout shifts where the `old_rect` was later occupied by an ad.
Some possible TODOs for follow-up PRs
- Tune scores
- Weigh the metric
- Write docs
- Audit Smoke Tests
- Audit for best practices
- Consider other metrics (# of ad related layout shifts or % of CLS attributable to ads in some way)
- The metric currently only checks the ad's iframe when counting ad shifts, but we may want to consider the ad's parent or grandparent element to handle padding, etc.
Feedback would be appreciated
=> Measure ad-related layout shift

lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/bid-request-from-page-start.js, lighthouse-plugin-publisher-ads/audits/first-ad-render.js, lighthouse-plugin-publisher-ads/audits/tag-load-time.js, lighthouse-plugin-publisher-ads/lighthouse-plugin-publisher-ads, lighthouse-plugin-publisher-ads/test/smoke/expectations/long-tasks.js
This resolves https://github.com/googleads/publisher-ads-lighthouse-plugin/issues/213.
=> Stop converting time-based numericValues to seconds.

lighthouse-plugin-publisher-ads/audits/bottleneck-requests.js, lighthouse-plugin-publisher-ads/lighthouse-plugin-publisher-ads, lighthouse-plugin-publisher-ads/test/smoke/expectations/script-injected.js
As the loading of ad scripts is required to load ads, they should not be considered a bottleneck.
=> Ignore ad scripts in bottleneck request audit.

lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js, lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js, lighthouse-plugin-publisher-ads/package.json, package.json, yarn.lock
Only notable change to us (afaik) is https://github.com/GoogleChrome/lighthouse/pull/11079 and a typescript update (since new LH code uses `@ts-expect-error` which was introduced recently).
=> Use lighthouse v6.2.0

lighthouse-plugin-publisher-ads/lighthouse-plugin-publisher-ads
This accidentally made it into https://github.com/googleads/publisher-ads-lighthouse-plugin/pull/216.
=> Delete unused symlink.

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature-request.md
Add templates for filing bugs and FRs. We have one template so the flow for filing a new issue shows two options: doc feedback and blank issue, but the link for filing a blank issue is not obvious.
=> Add templates for bugs and FRs

lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js, lighthouse-plugin-publisher-ads/audits/gpt-bids-parallel.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/tsconfig.json, lighthouse-plugin-publisher-ads/utils/bidder-patterns.js, lighthouse-plugin-publisher-ads/utils/graph.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Closes #212 
Also updates the critical path audit to show party alongside URL.
=> Show name + URL instead of abbreviated URLs in reports

lighthouse-plugin-publisher-ads/utils/graph.js
I noticed that GPT was sometimes omitted from the critical path. This probably indicates that there is some gap in the dependency graph. Rather than fix the underlying bug I decided to do a bandaid fix for now by forcing GPT/AdSense into the graph. I expect to file a lighthouse core issue if I notice anything specific
=> Ensure GPT is included in the request dependency graph

docs/audits/viewport-ad-density.md, lighthouse-plugin-publisher-ads/audits/viewport-ad-density.js, lighthouse-plugin-publisher-ads/messages/common-strings.js, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/messages/locales/en-XL.json, lighthouse-plugin-publisher-ads/test/audits/viewport-ad-density_test.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/lazy-load.js
Closes #209 
Note the better ads standard defines ad density as the ratio between sum of ad heights over content length, but content length is not well defined. It should include logos and footers, but it can be challenging to measure with lazy loading if not all ads are loaded immediately. For synthetic testing, I chose the content length to be 1 viewport after the midpoint of the last ad.
On desktop we measure each column of ads separately.
=> Measure ad density vertically

lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js, lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/messages/locales/en-XL.json, lighthouse-plugin-publisher-ads/plugin.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/deprecated-api-usage.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/gpt-errors-overall.js
We'll plan to set scores in a potential new scoring update.
=> Temporarily set GPT API audits as informational

lighthouse-plugin-publisher-ads/audits/total-ad-blocking-time.js, lighthouse-plugin-publisher-ads/lighthouse-plugin-publisher-ads, lighthouse-plugin-publisher-ads/messages/en-US.json, lighthouse-plugin-publisher-ads/messages/locales/en-XL.json, lighthouse-plugin-publisher-ads/plugin.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/not-applicable.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Note this takes a slightly different approach by having a table under the metrics section
Docs to come in a follow-up PR
=> New audit for a total ad blocking time metric

lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js, lighthouse-plugin-publisher-ads/test/smoke/expectations/cumulative-ad-shift.js, lighthouse-plugin-publisher-ads/test/smoke/fixtures/layout-shift.html, lighthouse-plugin-publisher-ads/test/smoke/smoke-test-dfns.js
- Don't count cases where an ad shifted but didn't cause the shift. Note that this approach only counts expansions (not shrinking/collapsing) since we only know the final ad size. Thanks @jonkeller for developing the algorithm.
- Count layout shifts that occur a frame after an ad script executes as an ad-attributable layout shift. This should capture shrinking/collapsing by GPT.
=> Update cumulative ad shift computation

docs/audits/script-injected-tags.md, docs/audits/viewport-ad-density.md
Looks like Copybara incorrectly reverted some doc changes in https://github.com/googleads/publisher-ads-lighthouse-plugin/commit/a120680911a50ecb7c85e1814612cd9273c060f8. This was probably due to the original PRs being manually submitted before Copybara could import the changes.
=> Revert unintended changes to audit documentation

lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js, lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js, lighthouse-plugin-publisher-ads/audits/async-ad-tags.js, lighthouse-plugin-publisher-ads/audits/duplicate-tags.js, lighthouse-plugin-publisher-ads/audits/full-width-slots.js, lighthouse-plugin-publisher-ads/audits/loads-ad-tag-over-https.js, lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js, lighthouse-plugin-publisher-ads/computed/tag-load-time.js, lighthouse-plugin-publisher-ads/test/utils/array_test.js, lighthouse-plugin-publisher-ads/test/utils/resource-classification_test.js, lighthouse-plugin-publisher-ads/utils/network-timing.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Node 10 added a global [`URL`](https://nodejs.org/api/globals.html#globals_url). The alias under `require('url').URL` is completely equivalent, except for some reason all the Node URL polyfills don't seem to bother to add `URL` to the '`url'` module and so it doesn't work automatically when bundled (using the default browserify and rollup polyfills, at least).
This has always worked anyways in Lighthouse because the library `robots-parser` gets `URL` the same way and so it's had to be manually patched, but the way we did it was kind of a hack. We have to change how we patch it in Lighthouse so I was trying to remember why we did it this hacky way (goes back to https://github.com/GoogleChrome/lighthouse/pull/5293) and realized pubads also needed it.
This PR isn't pressing because we still …
=> use global URL instead of node url module

lighthouse-plugin-publisher-ads/test/utils/resource-classification_test.js, lighthouse-plugin-publisher-ads/utils/resource-classification.js
Running Lighthouse tests with the `publisher-ads-lighthouse-plugin` increases runtime significantly.
Via the CLI on an M1 MacBook Pro, the following increase in runtime was observed for the following sites
* https://www.cnn.com - 8s
* https://www.wired.com - 6s
* https://google.com - 942ms
There is a relationship between the number of resources loaded on a page and the increase in execution time.
This issue was initially detected when adding the plugin to a suite of tests evaluating ~160 different domains. Average Lighthouse run time increased from 20s to 34s.
- Environment (CLI or web service): cli and node package
- Version: 1.5.5, Lighthouse 9.2.0 and 9.3.1 
- URL: https://www.cnn.com
- Settings: n/a
To reproduce:
1. Run 
```
lighthouse https://www.cnn.com …
```
=> Fix long execution times caused by isAdRelated

lighthouse-plugin-publisher-ads/test/smoke/expectations/cumulative-ad-shift.js
The underlying calculation of these appears to have shifted. 
We should evaluate if scoring should be adjusted accordingly.
=> Update cumulative-ad-shift smoke test thresholds.
