- lighthouse-plugin-ad-speed-insights/audits/ad-top-of-viewport.js
- lighthouse-plugin-ad-speed-insights/audits/ads-in-viewport.js
- lighthouse-plugin-ad-speed-insights/audits/duplicate-tags.js
- lighthouse-plugin-ad-speed-insights/audits/serial-header-bidding.js
- lighthouse-plugin-ad-speed-insights/audits/static-ad-tags.js
- lighthouse-plugin-ad-speed-insights/test/audits/serial-header-bidding_test.js
Modify notApplicable message punctuation for consistency.
> Make serial header bidding not applicable if no bid records.

- .travis.yml
- lighthouse-plugin-ad-speed-insights/test/utils/geometry_test.js
Fix line length in geometry_test.js, hopefully travis prevents this
going forward :).
> Include .travis.yml for CI testing.

- .gitignore
So that I never commit them ever again!
> Ignore vimdiff files

- lighthouse-plugin-ad-speed-insights/audits/script-injected-tags.js
- lighthouse-plugin-ad-speed-insights/audits/static-ad-tags.js
- lighthouse-plugin-ad-speed-insights/utils/resource-classification.js
Also fixes a false positive for dynamic loading
> Add line numbers for script injected tags

- lighthouse-plugin-ad-speed-insights/audits/ad-request-critical-path.js
- lighthouse-plugin-ad-speed-insights/audits/idle-network-times.js
- lighthouse-plugin-ad-speed-insights/utils/graph.js
- yarn.lock
Also includes some incidental formatting changes. I reverted most formatting diffs but left others in
> Include bid requests in critical path

- README.md
Update the readme to include a few Lighthouse options that I find useful.
> Document a few lighthouse options in README

- README.md
s/Ad Speed Insights/Publisher Ads Audits for Lighthouse/g
> Change Ad Speed Insights to Publisher Ads Audits for Lighthouse

- lighthouse-plugin-ad-speed-insights/messages/en-US.json
Per Rob Hazan's request, I've performed a review of the language in Publisher Ads Audits for Lighthouse audit messages.
I've corrected the punctuation per the Google Developer Style Guide and made a few changes for grammar and clarity in the messages. 
I may take a second pass at a later date.
> Update grammar and clarity for audit messages

- lighthouse-plugin-ad-speed-insights/messages/en-US.json
This resolves issue with browerify's util shim.
> Update messages to only accept strings.

- lighthouse-plugin-ad-speed-insights/messages/en-US.json
- lighthouse-plugin-ad-speed-insights/utils/bidder-patterns.js
- Remove unnecessary escaping
- Properly escape periods
- Include coverage for a couple common bidding scripts
> Update bid patterns regexps

- lighthouse-plugin-publisher-ads/audits/first-ad-paint.js
- lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js
- lighthouse-plugin-publisher-ads/package.json
- lighthouse-plugin-publisher-ads/test/utils/array_test.js
- lighthouse-plugin-publisher-ads/utils/array.js
- lighthouse-plugin-publisher-ads/yarn.lock
- package.json
- yarn.lock
Also does some revisions in utils/array.js to remove the use of `any` and fixes a bug where `array#bucket` skips falsey values, in particular 0.
> Upgrade to Typescript v 3.5.1

- lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
- lighthouse-plugin-publisher-ads/tsconfig.json
- lighthouse-plugin-publisher-ads/utils/asserts.js
- lighthouse-plugin-publisher-ads/utils/graph.js
This is also fixes some TS errors that were not surfaced previously.
> Add a few core lighthouse types to tsconfig

- lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js
- lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js
- lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
- lighthouse-plugin-publisher-ads/audits/ad-top-of-viewport.js
- lighthouse-plugin-publisher-ads/audits/ads-in-viewport.js
- lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
- lighthouse-plugin-publisher-ads/audits/idle-network-times.js
- lighthouse-plugin-publisher-ads/audits/script-injected-tags.js
- lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js
- lighthouse-plugin-publisher-ads/audits/static-ad-tags.js
- lighthouse-plugin-publisher-ads/messages/en-US.json
- lighthouse-plugin-publisher-ads/plugin.js
> Externalizes heading strings

- lighthouse-plugin-publisher-ads/test/audits/ad-request-from-page-start_test.js
- lighthouse-plugin-publisher-ads/test/audits/ad-request-from-tag-load_test.js
- lighthouse-plugin-publisher-ads/test/audits/full-width-slots_test.js
- lighthouse-plugin-publisher-ads/test/utils/resource-classification_test.js
- lighthouse-plugin-publisher-ads/utils/resource-classification.js
> Update isGptAdRequest() to only look at URL and resource time.

- lighthouse-plugin-publisher-ads/computed/ad-paint-time.js
I suspect we're not counting ad paint due to nested iframes. That is, the top iframe won't get a `firstPaint` event while a child frame does. Long term we should search child frames for `firstPaint` event but we fall back to the time of the first response in the short term
> Fall back to resource time for first ad paint when no paint is available

- lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js
- lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js
- lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
- lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js
- lighthouse-plugin-publisher-ads/audits/ad-request-from-tag-load.js
- lighthouse-plugin-publisher-ads/audits/ads-in-viewport.js
- lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
- lighthouse-plugin-publisher-ads/audits/first-ad-paint.js
- lighthouse-plugin-publisher-ads/audits/idle-network-times.js
- lighthouse-plugin-publisher-ads/audits/script-injected-tags.js
- lighthouse-plugin-publisher-ads/audits/static-ad-tags.js
- lighthouse-plugin-publisher-ads/audits/tag-load-time.js
- lighthouse-plugin-publisher-ads/messages/en-US.json
- lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
Modify i18n strings for compatibility with Google's translation service.
> Fix i18n strings

- lighthouse-plugin-publisher-ads/audits/first-ad-render.js
- lighthouse-plugin-publisher-ads/computed/ad-render-time.js
- lighthouse-plugin-publisher-ads/messages/common-strings.js
- lighthouse-plugin-publisher-ads/messages/en-US.json
- lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
- lighthouse-plugin-publisher-ads/plugin.js
> Rename ad paint to ad render

- lighthouse-plugin-publisher-ads/audits/script-injected-tags.js
- lighthouse-plugin-publisher-ads/messages/en-US.json
- lighthouse-plugin-publisher-ads/messages/locales/en-XL.json
Update link in `script-injected-tags` audit to point to developers.google.com
> Update link in `script-injected-tags` audit.

- lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
This resolves https://github.com/googleads/publisher-ads-lighthouse-plugin/issues/163 by filtering out the problem resources seen in the bug, however we were unable to repo so this likely does not solve the core issue. We will keep an eye on this problem going forward.
> Filter out invalid resources from ad request waterfall.

- lighthouse-plugin-publisher-ads/utils/network-timing.js
Currently we update the result map twice if there are two network records for this same script. In practice this means we'll show high load times for gpt.js if it's prefetched. Only the script-injected-tags audit should be affected since it displays script load times rather than network times.
> Bug fix: Avoid double simulating script load times

- lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js
- lighthouse-plugin-publisher-ads/audits/bid-request-from-page-start.js
- lighthouse-plugin-publisher-ads/audits/first-ad-render.js
- lighthouse-plugin-publisher-ads/audits/tag-load-time.js
Dynamicize metric thresholds such that appropriate values are used based on use of simulation.
> Dynamicize metric thresholds such that appropriate values are used.

- lighthouse-plugin-publisher-ads/package.json
- lighthouse-plugin-publisher-ads/test/smoke/config.js
- lighthouse-plugin-publisher-ads/test/smoke/expectations/lazy-load.js
- lighthouse-plugin-publisher-ads/test/smoke/expectations/long-tasks.js
- lighthouse-plugin-publisher-ads/test/smoke/expectations/render-blocking-tags.js
- lighthouse-plugin-publisher-ads/test/smoke/expectations/script-injected.js
- lighthouse-plugin-publisher-ads/test/smoke/fixtures/slowly-inject-gpt.js
- lighthouse-plugin-publisher-ads/test/smoke/run-smoke.js
- lighthouse-plugin-publisher-ads/test/smoke/smoke-test-dfns.js
- lighthouse-plugin-publisher-ads/tsconfig.json
- package.json
- yarn.lock
This resolves https://github.com/googleads/publisher-ads-lighthouse-plugin/issues/200
This exposed https://github.com/googleads/publisher-ads-lighthouse-plugin/issues/203 which I'll plan to look into in the near future.
> Fix build, upgrade to v1.1.0

- docs/audits/ad-request-from-page-start.md
- docs/audits/ad-request-from-tag-load.md
- docs/audits/tag-load-time.md
Also update tables for other metrics
> Document metrics for AMP tags

- docs/audits/deprecated-api-usage.md
- docs/audits/gpt-errors-overall.md
- docs/audits/serial-header-bidding.md
> Adding docs for GPT API audits

- lighthouse-plugin-publisher-ads/package.json
- lighthouse-plugin-publisher-ads/test/smoke/expectations/script-injected.js
- lighthouse-plugin-publisher-ads/test/utils/network_test.js
- lighthouse-plugin-publisher-ads/yarn.lock
- package.json
- yarn.lock
Upgrade other deps to latest versions to ensure compatibility.
Update tests as needed.
> Upgrade Lighthouse to v7.3.0.

- lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
> Include pubads_impl in the critical path

- lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js
See https://web.dev/evolving-cls/ and https://web.dev/cls-web-tooling/ for reference
> Limit cumulative ad shift measurement to a session window

- lighthouse-plugin-publisher-ads/package.json
- package.json
v1.5.3 was bad. Replacing it with v1.5.4.
> Update to v1.5.4

- lighthouserc.js
Update core timing thresholds to reduce flakiness for fast-ads mock page.
> Update Lighthouse CI thresholds

- lighthouse-plugin-publisher-ads/audits/ad-blocking-tasks.js
- lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js
- lighthouse-plugin-publisher-ads/audits/ad-request-critical-path.js
- lighthouse-plugin-publisher-ads/audits/ad-request-from-page-start.js
- lighthouse-plugin-publisher-ads/audits/ad-request-from-tag-load.js
- lighthouse-plugin-publisher-ads/audits/ad-top-of-viewport.js
- lighthouse-plugin-publisher-ads/audits/ads-in-viewport.js
- lighthouse-plugin-publisher-ads/audits/async-ad-tags.js
- lighthouse-plugin-publisher-ads/audits/bid-request-from-page-start.js
- lighthouse-plugin-publisher-ads/audits/blocking-load-events.js
- lighthouse-plugin-publisher-ads/audits/bottleneck-requests.js
- lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js
- lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
- lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
- lighthouse-plugin-publisher-ads/audits/first-ad-render.js
- lighthouse-plugin-publisher-ads/audits/full-width-slots.js
- lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
- lighthouse-plugin-publisher-ads/audits/idle-network-times.js
- lighthouse-plugin-publisher-ads/audits/loads-ad-tag-over-https.js
- lighthouse-plugin-publisher-ads/audits/loads-gpt-from-official-source.js
- lighthouse-plugin-publisher-ads/audits/script-injected-tags.js
- lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js
- lighthouse-plugin-publisher-ads/audits/tag-load-time.js
- lighthouse-plugin-publisher-ads/audits/total-ad-blocking-time.js
- lighthouse-plugin-publisher-ads/audits/viewport-ad-density.js
- lighthouse-plugin-publisher-ads/messages/common-strings.js
- lighthouse-plugin-publisher-ads/plugin.js
- lighthouse-plugin-publisher-ads/typings/lighthouse.d.ts
ref https://github.com/GoogleChrome/lighthouse/pull/14251
> replace createMessageInstanceIdFn with createIcuMessageFn

- lighthouse-plugin-publisher-ads/audits/loads-gpt-from-official-source.js
> use global URL instead of node url module

- lighthouse-plugin-publisher-ads/audits/ad-render-blocking-resources.js
- lighthouse-plugin-publisher-ads/audits/async-ad-tags.js
- lighthouse-plugin-publisher-ads/audits/blocking-load-events.js
- lighthouse-plugin-publisher-ads/audits/deprecated-api-usage.js
- lighthouse-plugin-publisher-ads/audits/duplicate-tags.js
- lighthouse-plugin-publisher-ads/audits/full-width-slots.js
- lighthouse-plugin-publisher-ads/audits/gpt-bids-parallel.js
- lighthouse-plugin-publisher-ads/audits/gpt-errors-overall.js
- lighthouse-plugin-publisher-ads/audits/idle-network-times.js
- lighthouse-plugin-publisher-ads/audits/loads-ad-tag-over-https.js
- lighthouse-plugin-publisher-ads/audits/loads-gpt-from-official-source.js
- lighthouse-plugin-publisher-ads/audits/script-injected-tags.js
- lighthouse-plugin-publisher-ads/audits/serial-header-bidding.js
- lighthouse-plugin-publisher-ads/audits/total-ad-blocking-time.js
- lighthouse-plugin-publisher-ads/computed/ad-lantern-metric.js
- lighthouse-plugin-publisher-ads/computed/long-tasks.js
- lighthouse-plugin-publisher-ads/test/audits/async-ad-tags_test.js
- lighthouse-plugin-publisher-ads/test/audits/full-width-slots_test.js
- lighthouse-plugin-publisher-ads/test/audits/loads-ad-tag-over-https_test.js
- lighthouse-plugin-publisher-ads/tsconfig.json
- lighthouse-plugin-publisher-ads/typings/lighthouse.d.ts
- lighthouse-plugin-publisher-ads/utils/graph.js
- lighthouse-plugin-publisher-ads/utils/network-timing.js
- package.json
- yarn.lock
ref https://github.com/GoogleChrome/lighthouse/pull/14352
> update lighthouse computed artifacts to use named exports
